apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-24T23:18:33Z"
  labels:
    app: go-dep
  name: go-dep
  namespace: default
  resourceVersion: "19214"
  uid: aa76f226-19e8-4811-bbe0-747c8a8a13f4
spec:
  clusterIP: 10.102.94.45
  clusterIPs:
  - 10.102.94.45
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31681
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: go-dep
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}